---
admins:
  - name: agoofy
    password: schule
    groups:
      # localized! use debug/getLocalGroups.yml for infos about groups
      - Administratoren

  - name: bgoofy
    password: schule
    groups:
      - Administratoren
# normal users
users:
