---
- set_fact:
    pwd: '{{ item.0.password if ((global_admin_password is not defined) or (global_admin_password|length == 0)) else global_admin_password }}'
  loop: "{{ admins|subelements('groups') }}"
  loop_control:
    label: '{{ item.0.name }}'

- name: Debug
  debug:
    msg:
      - '{{ item.0.name }}, {{ item.0.password }}, {{ item.1 }}'
      - 'Password: {{ pwd }}'

  loop: "{{ admins|subelements('groups') }}"
  loop_control:
    label: '{{ item.0.name }}'
