---
- name: Set up Python on Windows
  hosts: windows-target

  become_method: runas
  become_user: SYSTEM

  vars:
    python3_version: 3.6.0
    architecture: amd64
    python3_dl: C:\Users\{{ansible_user}}\Downloads\python-{{python3_version}}-{{architecture}}.exe

  tasks:

  - name: install python 3
    block:

    - name: "Check for{{python3_version}} installer"
      win_stat:
        path: "{{python3_dl}}"
      register: python3_dl_info

    - name: "Download python{{ python3_version }}"
      win_get_url:
        url: 'https://www.python.org/ftp/python/{{python3_version}}/python-{{python3_version}}-{{architecture}}.exe'
        dest: '{{python3_dl}}'
      when: not python3_dl_info.stat.exists

    - name: "Install python{{python3_version}}"
      become: yes
      win_package:
        path: "{{python3_dl}}"
        state: present
        product_id: "python_{{python3_version}}"
        arguments: /quiet InstallAllUsers=1 InstallLauncherAllUsers=1 Include_lib=1 Include_pip=1 Include_tcltk=0 PrependPath=1 Include_test=1 Include_tools=1 TargetDir=C:\Python{{python3_version}}